config/routes.rb
Rails.application.routes.draw do

  get 'tutoworlds/show'

  get 'recaps/show'
  post 'recaps/show'
  patch 'recaps/update'

  get 'fights/show'
  post 'fights/show'
  get 'fights/update'
  patch 'fights/update'

  get 'worlds/show'
  put 'worlds/update', to: 'worlds#update'
  scope '(:locale)', locale: /fr|es/ do
    root 'high_voltage/pages#show', id: 'home', as: :root_with_locale
    get '/pages/:id' => 'high_voltage/pages#show', :as => :page, :format => false
    resource :username, only: [:new, :create]
    devise_for :users
    resource :user, only: [:show, :update]
    get '/user/collection', to: 'users#collection'
    get '/user/stats', to: 'users#stats'
  end

  resources :items

end

app/models/world.rb
# == Schema Information
#
# Table name: worlds
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  background  :string
#  max_x       :integer
#  max_y       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  usercount   :integer          default(0)
#  tuto        :boolean          default(TRUE)
#

class World < ActiveRecord::Base
  has_many :users
  has_many :events
  has_many :items
  validates :name, presence: true
  validates :background, presence: true
  validates :max_x, presence: true
  validates :max_y, presence: true
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  respond_to :js, only: [:update]
  before_action :check_notif

  def show
    set_player_position
    position_other_players_in_grid
    position_items_in_grid
    kinder_surprise
    set_world_info
    sojajauge
    available_move_items
    livenews
    tuto
  end

  def update
    set_player_position
    check_if_move_or_grab_update
    position_other_players_in_grid
    position_items_in_grid
    kinder_surprise
    set_world_info
    sojajauge
    available_move_items
    livenews
    tuto
  end

  private

  def set_player_position
    @x_player = current_user.x
    @y_player = current_user.y
    @x_shift = @x_player - 3
    @y_shift = @y_player - 3
  end

  def translate_player_position
    @item_type_id = params[:item_type_id]
    @new_position = params[:new_position].split("")
    current_user.x = @new_position[0].to_i + @x_shift
    current_user.y = @new_position[1].to_i + @y_shift
    if @item_type_id == 'feet'
      @consumption = 4
    else
      @item = current_user.items.where(item_type_id: @item_type_id).first
      @consumption = @item.item_type.consumption
      @item.broken_count += 1
      @item.save

      if @item.broken_count >= @item.item_type.lifetime
        # normal items
        if @item.tuto = false
          @item.user_id = nil
          @item.world_id = current_user.world_id
          set_item_position_after_broken
          while User.where(world_id: @item.world_id, x: @item.x, y: @item.y).exists? do
            set_item_position_after_broken
          end
          @item.broken_count = 0
          @item.save
        # items spawned for the tutoriel that must disappear
        else
          @item.user_id = nil
          @item.save
        end

        # event d'objet casse
        broken = Event.new
        broken[:name] = "broken"
        broken[:world_id] = current_user.world_id
        broken[:user_id] = current_user.id
        broken[:item_type_id] = @item.item_type.id
        broken[:read] = false
        broken.save
      end
    end
    current_user.soja -= @consumption
    current_user.save
    @x_shift = current_user.x - 3
    @y_shift = current_user.y - 3
  end

  def available_move_items
    @move_item_types = current_user.item_types.where(kind: 'Movement').order(consumption: :asc)
  end

  def position_other_players_in_grid
    @players = User.in_area(current_user)
    @players_on_map = {}
    @players.each do |player|
     @players_on_map[("#{player[:x] - @x_shift}#{player[:y] - @y_shift}").to_sym] = player
    end
  end

  def position_items_in_grid
    @items = Item.in_area(current_user)
    @items_on_map = {}
    @items.each do |item|
      @items_on_map[("#{item[:x] - @x_shift}#{item[:y] - @y_shift}").to_sym] = item
    end
  end

  def kinder_surprise
    @kinder = Item.where(world_id: current_user.world_id, x: current_user.x, y: current_user.y)
  end

  def add_item_to_user
    item_id = params[:item_id]
    if current_user.items.count < 9
      new_item = kinder_surprise.find(item_id)
      new_item.world_id = nil
      new_item.x = nil
      new_item.y = nil
      new_item.user_id = current_user.id
      new_item.save
    end
  end

  def check_if_move_or_grab_update
    @choice = params[:choice]
    case @choice
    when "move" then translate_player_position
    when "grab" then add_item_to_user
    end
  end

  def set_world_info
    # background info
    @world_background = current_user.world.background
    @max_x =  current_user.world.max_x
    @max_y =  current_user.world.max_y
    # user infos
    @life = current_user.life
    @soja = current_user.soja
    case current_user.crew
    when "avocado" then @ennemies = "salmons"
    when "salmon" then @ennemies = "avocados"
    when "bastardo" then @ennemies = "everyone, you bastard"
    when "babyrice" then @ennemies = "everyone"
    end
    @info = ".info" + (rand(10) + 1).to_s
  end

  def sojajauge
    @soja = current_user.soja
    case @soja
    when 0 then @jauge = "empty.png"
    when 1...3 then @jauge = "verylow.png"
    when 3...12 then @jauge = "low.png"
    when 12 then @jauge = "half.png"
    when 13...24 then @jauge = "almostfull.png"
    when 24 then @jauge = "full.png"
    when 25..50 then @jauge = "overfull.gif"
    end
  end

  def lifebar(player)
    case player.life
    when 10 then return "full"
    when 6..10 then return "almostfull"
    when 5 then return "half"
    when 2..5 then return "low"
    when 1 then return "verylow"
    end
  end

  def set_item_position_after_broken
    @item.x = rand(1..current_user.world.max_x)
    @item.y = rand(1..current_user.world.max_y)
  end

  def tuto
    if current_user.world.tuto
      case current_user.x
      when 1
        @tuto_text = "Hey! Touch the cell next to " + current_user.name + " to move there!"
      when 2
        if current_user.items.count == 0
          @tuto_text = "Wow! So cool! <br>  Keep going right!"
        else
          @tuto_text = "If I were you, I'd go right."
        end
      when 3
        if current_user.items.count == 0
          @tuto_text = "Wait! Is that a box on your right? <br> Go check it out."
        else
          @tuto_text = "You should keep going right, little maki."
        end

      when 4
        if current_user.items.count == 0
          @tuto_text = "Touch the bouncing box to see what\'s inside!"
        else
          @tuto_text = "Nice items! <br> You can now go further and hit harder!"
        end
      when 5
        @tuto_text = "Each move or attack you make costs some soy sauce."
      when 6
        @tuto_text = "Let\'s teleport so I can explain you something, " + current_user.name + "."
      # in case user goes to far by using several browsers
      when 7
        @tuto_text = "WOOOW! Reload the page please!"
        current_user.x = 6
        current_user.save
      end
      # in case user goes back and lacks soy sauce
      if current_user.soja < 5
        current_user.soja = 50
        current_user.save
      end
    end
  end

  def livenews
    @liveevents = []
    lastevents = Event.where({world_id: current_user.world_id}).last(10)
    lastevents.each do |event|
      eventhash = {}
      eventhash[:date] = event.created_at

      name = event.name
      userid = event.user_id
      otheruserid = event.other_user_id

      if otheruserid
        eventhash[:user_name] = User.find(userid).name
        eventhash[:user_crew] = User.find(userid).crew
        eventhash[:other_user_name] = User.find(otheruserid).name
        eventhash[:image] = "info/" + "fire.png"
      end

      @liveevents << eventhash
    end
  end

end

app/helpers/worlds_helper.rb
module WorldsHelper
end

app/views/worlds/_worldmap.html.erb
<div class='the-world'>
  <div class="container">
    <div class="row">

      <div class="col-xs-12 col-sm-4 col-sm-offset-4">

        <div class="worldmap default" data-bg='<%= world_background%>' data-maxx="<%= max_x %>" data-maxy="<%= max_y %>">
          <!-- first row -->
          <div class="cell" data-cell="11"></div>
          <div class="cell" data-cell="21"></div>
          <div class="cell" data-cell="31"></div>
          <div class="cell" data-cell="41"></div>
          <div class="cell" data-cell="51"></div>
          <!-- second row -->
          <div class="cell" data-cell="12"></div>
          <div class="cell welcome" data-cell="22"></div>
          <div class="cell welcome" data-cell="32"></div>
          <div class="cell welcome" data-cell="42"></div>
          <div class="cell" data-cell="52"></div>
          <!-- third row -->
          <div class="cell" data-cell="13"></div>
          <div class="cell welcome" data-cell="23"></div>
          <div class="cell" id='player' data-cell="33" data-shift-x="<%= x_shift %>" data-shift-y="<%= y_shift %>" data-playercrew="<%= current_user.crew %>"></div>
          <div class="cell welcome" data-cell="43">
            <!-- arrow to indicate cells in tuto -->
            <% if current_user.world.tuto %>
              <% if current_user.x < 4 && current_user.items.count == 0 %>
                <%= image_tag "info/arrow_top.gif", class:'bounce-arrow-next' %>
              <% elsif current_user.x == 4 && current_user.items.count == 0 %>
                <%= image_tag "info/arrow_top.gif", class:'bounce-arrow-me' %>
              <% elsif current_user.x == 5 %>
                <%= image_tag "info/arrow_yellow.gif", class:'bounce-arrow-soy' %>
              <% end %>
            <% end %>
          </div>
          <div class="cell" data-cell="53"></div>
          <!-- fourth row -->
          <div class="cell" data-cell="14"></div>
          <div class="cell welcome" data-cell="24"></div>
          <div class="cell welcome" data-cell="34"></div>
          <div class="cell welcome" data-cell="44"></div>
          <div class="cell" data-cell="54"></div>
          <!-- fifth row -->
          <div class="cell" data-cell="15"></div>
          <div class="cell" data-cell="25"></div>
          <div class="cell" data-cell="35"></div>
          <div class="cell" data-cell="45"></div>
          <div class="cell" data-cell="55"></div>
          <!-- life and soy sauce jauges -->
          <div id="life-holder">
            <%= image_tag "info/heart.png", id: "heart" %>
            <div id="life" class="text-center">
              x<%= life %>
            </div>
          </div>
          <% if current_user.world.tuto %>
            <div id="jauge-holder" class="jauge-tuto">
          <% else %>
            <div id="jauge-holder">
          <% end %>
            <%= image_tag "info/soja_" + jauge, id: "jauge" %>
            <div id="soja" class="text-center">
              <%= soja %>
            </div>
          </div>
          <%= image_tag "animatedpin.gif", id: "pin" %>
        </div>

        <!-- box content -->
        <div class="items-list hidden">
          <% if current_user.items.count < 9 %>
            <h3>Items in the box</h3>
          <% else %>
            <h3>Your bag is full!</h3>
          <% end %>
          <table class='item-table'>
            <% kinder.each do |item| %>
              <tr>
                <td class='vert-align'><%= image_tag "items/" + item.item_type.picture, class:'thumb' %></td>
                <td class='vert-align'><%= item.item_type.name %></td>
                <% if current_user.items.count < 9 %>
                  <td class='vert-align text-center'>
                    <%= form_tag worlds_update_path, method: :put, remote: true do %>
                      <%= hidden_field_tag :choice, "grab" %>
                      <%= hidden_field_tag :item_id, item.id %>
                      <%= submit_tag "Grab", class: "confirm-grab" %>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </table>
        </div>

        <!-- Teleport -->

      <% if current_user.world.tuto && current_user.x == 6 %>
         <%= button_to " ", recaps_show_path, params: {"endtuto" => true }, method: :post, class: "teleport" %>
         <%= image_tag "info/arrow_top.gif", class: "arrow-teleport" %>
      <% end %>

      </div>

      <div class="col-xs-12 col-sm-4 col-sm-offset-4">
        <div class="info-bottom">

          <!-- anchorman -->

          <% if current_user.world.tuto %>

            <div class="news-info text-center">
              <div class="info-holder">
                <div class="col-xs-5"><%= image_tag "presentateur.gif", class: "profilepic" %></div>
                <div class="col-xs-6 text-left" id="anchorman-speech">
                  <% if current_user.world.tuto %>
                    <%= tuto_text.html_safe %>
                    <% if current_user.x == 6 %>
                      <%= button_to t('.confirm_attack'), fights_show_path, params: {"endtuto" => true }, class: "attack-opponent hidden" %>
                    <% end %>
                  <% else %>
                    <%= t(info, ennemies: ennemies) %>
                  <% end %>
                </div>
              </div>
            </div>

          <% else %>

          <!-- live news -->

          <div class="news-info">

            <div id="live-news-title">Live</div>

            <div id="live-news-content">
              <div class="row news-card">
                <% @liveevents.each do |event| %>
                  <% if event[:other_user_name] %>
                    <div class="col-xs-3 profilepic-holder"><%= image_tag "profilepics/" + event[:user_crew] + ".png", class: "live-news-avatar" %></div>
                    <div class="col-xs-9">
                      <p class="news-time"><%= image_tag "info/clock.png", class: "clock" %><%= time_ago_in_words(@liveevents.last[:date])%></p>
                      <p class="news-text"><%= event[:user_name] %> <%= image_tag event[:image], class: "eventimage" %> <%= event[:other_user_name] %> </p>
                    </div>
                  <% else %>
                      <div class="col-xs-3 profilepic-holder"></div>
                      <div class="col-xs-9">COUCOU</div>
                  <% end %>
                <% end %>
              </div>
            </div>


            <div id="view-leaderboard">view leaderboard</div>
          </div>

          <% end %>

          <!-- player self options -->
          <div class='my-maki hidden'>
            <div class='my-profile text-center'>
              <% if current_user.x == 4 && current_user.world.tuto && current_user.items.count == 0 %>
                <%= image_tag "info/arrow_right.gif", class:'bounce-arrow-right' %>
              <% else %>
                <%= form_tag user_path, method: :get do %>
                  <%= %>
                  <%= image_tag current_user.crew + '.png', class:'img-options-display' %>
                  <%= submit_tag t('.profile'), class: "confirm-action" %>
                <% end %>
              <% end %>
            </div>
            <div class='search-item text-center'>
              <%= image_tag 'items/noitem2.png', class:'img-options-display'%>
              <p class='text-fade2 text-center' type='submit'>Nothing here</p>
            </div>
            <div class='grab-item text-center'>
              <div class='open-close text-center'>
                <%= image_tag 'item_close.png', class:'img-options-display' %>
                <input class='confirm-action' value='Open Box' type='submit'></input>
              </div>
              <div class='open-close text-center hidden'>
                <%= image_tag 'item_open.png', class:'img-options-display' %>
                <input class='confirm-action' value='Close Box' type='submit'></input>
              </div>
            </div>
            <div class="clear"></div>
          </div>

          <!-- player moves options -->
          <div class='new-move scrolls text-center hidden'>

            <% if move_item_types.count > 0 %>
              <% move_item_types.each do |item_type| %>
                <div class="transportation-options bg-<%= item_type.consumption %>" >
                  <%= image_tag "items/" + item_type.picture, class:'img-options-display'%>
                  <div class="items_count"><h3>x<%= current_user.items.where(item_type: item_type.id).count%></h3></div>
                  <div class="consumption"><h3><%= item_type.consumption %>cl</h3></div>
                  <%= form_tag worlds_update_path, method: :put, remote: true do %>
                    <%= hidden_field_tag :choice, "move" %>
                    <%= hidden_field_tag :item_type_id, item_type.id %>
                    <%= hidden_field_tag :new_position,'',class:'new_position' %>
                    <% if current_user.soja >= item_type.consumption %>
                      <%= submit_tag item_type.name, class: "confirm-action minipulse" %>
                    <% else %>
                    <p class="not-possible"><%= t(".nosoy", missing_cl: item_type.consumption - current_user.soja) %></p>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>

            <div class="transportation-options bg-4" >
              <%= image_tag "items/default/bounce.png", class:'img-options-display' %>
              <div class="items_count"><h3>∞</h3></div>
              <div class="consumption"><h3>4cl</h3></div>
              <%= form_tag worlds_update_path, method: :put, remote: true do %>
                <%= hidden_field_tag :choice, "move" %>
                <%= hidden_field_tag :item_type_id, 'feet' %>
                <%= hidden_field_tag :new_position,'',class:'new_position' %>
                <% if current_user.soja >= 4 %>
                  <%= submit_tag "Bounce", class: "confirm-action minipulse" %>
                <% else %>
                <p class="not-possible"><%= t(".nosoy", missing_cl: 4 - current_user.soja) %></p>
                <% end %>
              <% end %>
            </div>


            <% if move_item_types.count == 0 %>
              <div class="transportation-options bg-2" >
                <% if current_user.world.tuto %>
                  <%= image_tag "info/arrow_left.gif", class:'bounce-arrow-left' %>
                <% else %>
                  <%= image_tag "items/noitem.png", class:'img-options-display' %>
                  <br>
                  <p class='text-fade text-center' type='submit'>You have no item.</p>
                <% end %>
              </div>
            <% end %>
          </div>

          <!-- other players infos & position on map -->
          <% players_on_map.each do |cell, player| %>
            <div class="cell-info text-center hidden" id="cell-info-<%= cell %>" data-x="<%= player.x - x_shift %>" data-y="<%= player.y - y_shift%>" data-crew="<%= player.crew %>" >
              <div class="info-holder">
                <div class="visitcard">
                  <div class="col-xs-5">
                    <div class="profilename"><%= player.name %></div>
                    <%= image_tag "profilepics/" + player.crew + ".png", class: "profilepic" %>
                  </div>
                  <div class="col-xs-7 profileinfos">
                    <p>
                      <%= image_tag "emblems/" + player.crew + ".gif", id: "emblem" %>
                      Team <%= player.crew %>
                    </p>
                    <p>
                      <%= image_tag "info/wasabi.png", class: "wasabi-opponent" %>
                      <%= player.wasabi %>g
                    </p>
                    <p><%= button_to t('.confirm_attack'), fights_show_path, params: {"defender" => player.id, "old_crew" => current_user.crew }, class: "attack-opponent hidden" %></p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>

          <!-- items position on map -->
          <% items_on_map.each do |cell, item| %>
            <div class="item-info text-center hidden" id="item-info-<%= cell %>" data-x="<%= item.x - x_shift %>" data-y="<%= item.y - y_shift%>" ></div>
          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/worlds/show.html.erb
<%= render 'worldmap',
  x_shift: @x_shift,
  y_shift: @y_shift,
  life: @life,
  soja: @soja,
  info: @info,
  ennemies: @ennemies,
  players_on_map: @players_on_map,
  items_on_map: @items_on_map,
  jauge: @jauge,
  move_item_types: @move_item_types,
  choice: @choice,
  kinder: @kinder,
  world_background: @world_background,
  max_x: @max_x,
  max_y: @max_y,
  tuto_text: @tuto_text
%>

app/views/worlds/show.js.erb
PubSub.publish('setWorld');
$('.the-world').replaceWith("<%= j render 'worldmap',
  x_shift: @x_shift,
  y_shift: @y_shift,
  life: @life,
  soja: @soja,
  info: @info,
  ennemies: @ennemies,
  players_on_map: @players_on_map,
  jauge: @jauge,
  items_on_map: @items_on_map,
  move_item_types: @move_item_types,
  choice: @choice,
  kinder: @kinder
 %>");

$('#player').addClass('hatch');

<% if @choice == 'grab' %>
  PubSub.publish('afterGrab');
<% end %>

app/views/worlds/update.js.erb
PubSub.publish('setWorld');
$('.the-world').replaceWith("<%= j render 'worldmap',
  x_shift: @x_shift,
  y_shift: @y_shift,
  life: @life,
  soja: @soja,
  info: @info,
  ennemies: @ennemies,
  players_on_map: @players_on_map,
  jauge: @jauge,
  items_on_map: @items_on_map,
  move_item_types: @move_item_types,
  choice: @choice,
  kinder: @kinder,
  world_background: @world_background,
  max_x: @max_x,
  max_y: @max_y,
  tuto_text: @tuto_text
 %>");

$('#player').addClass('hatch');

<% if @choice == 'grab' %>
  PubSub.publish('afterGrab');
<% end %>