config/routes.rb
Rails.application.routes.draw do

  get 'tutoworlds/show'

  get 'recaps/show'
  post 'recaps/show'
  patch 'recaps/update'

  get 'fights/show'
  post 'fights/show'
  get 'fights/update'
  patch 'fights/update'

  get 'worlds/show'
  put 'worlds/update', to: 'worlds#update'
  scope '(:locale)', locale: /fr|es/ do
    root 'high_voltage/pages#show', id: 'home', as: :root_with_locale
    get '/pages/:id' => 'high_voltage/pages#show', :as => :page, :format => false
    resource :username, only: [:new, :create]
    devise_for :users
    resource :user, only: [:show, :update]
    get '/user/collection', to: 'users#collection'
    get '/user/stats', to: 'users#stats'
  end

  resources :items

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  crew                   :string           default("babyrice")
#  soja                   :integer          default(24)
#  life                   :integer          default(10)
#  x                      :integer
#  y                      :integer
#  world_id               :integer
#  lowername              :string
#  soja_updated_at        :datetime
#  wasabi                 :integer          default(0)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_world_id              (world_id)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :world
  has_many :events
  has_many :received_events, class_name: 'Event', foreign_key: :other_user_id
  has_many :items
  has_many :item_types, -> { distinct }, through: :items
  validates :name, presence: true, uniqueness: true
  before_create { |user| user.lowername = user.name.downcase }

  after_create :preborn

  scope :in_area, ->(user) do
    where.not(id: user.id).
      where(world_id: user.world_id).
      where("x >= :min_x AND x <= :max_x AND y >= :min_y AND y <= :max_y",
        min_x: user.x - 2, max_x: user.x + 2,
        min_y: user.y - 2, max_y: user.y + 2
      )
  end

  def all_unread_events
    Event.where("(user_id = :user_id AND read = :unread)
      OR (other_user_id = :user_id AND read_other_user = :unread)",
      user_id:  self.id,
      unread:   false
    )
  end

  def preborn
    tutoworld = create_tuto_world
    create_item_for_tuto(tutoworld)
    set_player_on_tuto(tutoworld)
  end

  def born
    world = World.where('usercount < 50 AND tuto = false').order(usercount: :desc).limit(1).first
    self.world_id = world.id
    if world.users.empty?
      self.x = world.max_x / 2
      self.y = world.max_y / 2
    else
      set_position(world)
      while User.where(world_id: world.id, x: x, y: y).exists? || x >= world.max_x || x <= 0 || y >= world.max_y || y <= 0 do
        set_position(world)
      end
    end
    self.soja_updated_at = Time.now.at_beginning_of_hour
    self.soja = 50
    self.save

    #event of birth
    birth = Event.new
    birth[:name] = "birth"
    birth[:user_id] = self.id
    birth[:world_id] = self.world_id
    birth.save

    world.usercount += 1
    world.save
  end

  private

  def set_position(world)
    others = User.where(world_id: world.id)
    n      = others.sample
    self.x = rand((n.x - 2)..(n.x + 2))
    self.y = rand((n.y - 2)..(n.y + 2))
  end

  def create_tuto_world
    tutoworld = World.new
    tutoworld[:tuto] = true
    tutoworld[:name] = "tuto"
    tutoworld[:description] = "Still a babymaki"
    tutoworld[:background] = "tutoworld"
    tutoworld[:max_x] = 6
    tutoworld[:max_y] = 1
    tutoworld[:usercount] = 1
    tutoworld.save
    return tutoworld
  end

  def set_player_on_tuto(tutoworld)
    self.world_id = tutoworld.id
    self.x = 1
    self.y = 1
    self.soja_updated_at = Time.now.at_beginning_of_hour
    self.soja = 50
    self.save
  end

  def create_item_for_tuto(tutoworld)
    movement_typeid = ItemType.all.where(kind: "Movement").sample.id
    attack_typeid = ItemType.all.where(kind: "Attack").sample.id
    Item.create(item_type_id: movement_typeid, world_id: tutoworld.id, x: 4, y: 1, broken_count: 0, tuto: true)
    Item.create(item_type_id: attack_typeid, world_id: tutoworld.id, x: 4, y: 1, broken_count: 0, tuto: true)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :js, only: [:update]

  def show
    my_backpack
  end

  def update

    typeid = params[:item_type_id]

    item = Item.where(user_id: current_user.id, item_type_id: typeid).first

    item.user_id = nil
    item.world_id = current_user.world_id
    item.x = current_user.x
    item.y = current_user.y
    item.save

    my_backpack
  end

  private

  def my_backpack
    my_items_type = current_user.item_types.order(kind: :desc)
    #variable to display
    @mybackpack = {}
    @item_description = {}
    @item_t_id = {}
    @allitems_count = 0
    # compute their value
    my_items_type.each do |item_type|
      @mybackpack[item_type] = current_user.items.where(item_type: item_type.id).count
      # count all items
      @allitems_count += @mybackpack[item_type]
      @item_t_id[item_type] = item_type.id
      case item_type.kind
      when "Attack"
        @item_description[item_type] = "Attacks for " + item_type.consumption.to_s + " cl."
      when "Movement"
        @item_description[item_type] = "Moves for " + item_type.consumption.to_s + " cl."
      when "Useless"
        @item_description[item_type] = "Does nothing special."
      end
    end
    return @mybackpack
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<div class="profile-and-item">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">

      <div class='my-profile-main'>

        <div class="maki-in-landscape text-center">
          <%= link_to t('component.back'), worlds_show_path, class: "back-button" %>

          <%= image_tag "emblems/" + current_user.crew + ".gif", id:'crew-profile' %>

          <ul class='profile-info-crew'>
            <li><%= image_tag current_user.crew + ".gif", id: "maki-avatar", class:'floating' %></li>
            <li><h2 class= 'text-white-shadow'><%= current_user.name %></h2></li>
            <li><h2 class= 'text-white-shadow'>#team<%= current_user.crew %></h2></li>
          </ul>

        </div>

        <!-- box content -->
        <div class="my-items-list hidden">
          <h3>My Bag <span class="greytitle">(<%= allitems_count %>/9)</span></h3>
          <table class='item-table'>
            <% mybackpack.each do |item_type, item_count| %>
              <tr>
                <td class='vert-align drop-holder'><%= image_tag "items/" + item_type.picture, class:'thumb' %>
                  <% if item_count > 1 %>
                      <%= form_tag user_path, method: :put, remote: true do %>
                        <%= hidden_field_tag :item_type_id, item_t_id[item_type] %>
                        <%= submit_tag "Drop one", class: "confirm-grab align-items-profile" %>
                      <% end %>
                  <% else %>
                      <%= form_tag user_path, method: :put, remote: true do %>
                        <%= hidden_field_tag :item_type_id, item_t_id[item_type] %>
                        <%= submit_tag "Drop it", class: "confirm-grab align-items-profile" %>
                      <% end %>
                  <% end %>
                </td>
                <td class='vert-align'>
                  <ul class='my-items-details'>
                    <li class='title'>
                      <%= item_type.name %>
                      (x<%= item_count %>)
                    </li>
                    <li class='content greytitle'><%= item_type.joke %></li>
                    <li class='content greytitle'> <%= item_description[item_type] %></li>
                    <% if item_type.life_impact %>
                      <li class='content'><span class="greytitle">Life Impact:</span>
                        <% item_type.life_impact.times do %>
                          <%= image_tag 'info/fire.png', class:'mini' %>
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                </td>
              </tr>
            <% end %>
          </table>
        </div>

      </div>

        <!-- profile self options -->
        <div class='my-profile-menu'>
          <div class='my-account text-center'>
            <%= image_tag 'profile/account.png', class:'img-options-display' %><br>
            <%= link_to edit_user_registration_path do %>
              <input class='confirm-action' value='My Account' type='submit'></input>
            <% end %>
          </div>
          <div class='my-items text-center'>
            <div class='my-open-close text-center'>
              <%= image_tag 'bag_close.png', class:'img-options-display' %>
              <input class='confirm-action' value='Open Bag' type='submit'></input>
            </div>
            <div class='my-open-close text-center hidden'>
              <%= image_tag 'bag_open.png', class:'img-options-display' %>
              <input class='confirm-action' value='Close Bag' type='submit'></input>
            </div>
          </div>
          <div class="clear"></div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/users/collection.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="text-center">

        <div class='top-menu'>
          <%= link_to t('component.back'), user_path, class:'btn btn-default' %>
          <h2>Collection</h2>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'profile',
  allitems_count: @allitems_count,
  item_description: @item_description,
  mybackpack: @mybackpack,
  item_t_id: @item_t_id
%>

app/views/users/stats.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="text-center">

        <div class='top-menu'>
          <%= link_to t('component.back'), user_path, class:'btn btn-default' %>
          <h2>Stats</h2>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/users/update.js.erb
$('.profile-and-item').replaceWith("<%= j render 'profile',
  allitems_count: @allitems_count,
  item_description: @item_description,
  mybackpack: @mybackpack,
  item_t_id: @item_t_id
 %>");

PubSub.publish('profileDisplay');