config/routes.rb
Rails.application.routes.draw do

  get 'tutoworlds/show'

  get 'recaps/show'
  post 'recaps/show'
  patch 'recaps/update'

  get 'fights/show'
  post 'fights/show'
  get 'fights/update'
  patch 'fights/update'

  get 'worlds/show'
  put 'worlds/update', to: 'worlds#update'
  scope '(:locale)', locale: /fr|es/ do
    root 'high_voltage/pages#show', id: 'home', as: :root_with_locale
    get '/pages/:id' => 'high_voltage/pages#show', :as => :page, :format => false
    resource :username, only: [:new, :create]
    devise_for :users
    resource :user, only: [:show, :update]
    get '/user/collection', to: 'users#collection'
    get '/user/stats', to: 'users#stats'
  end

  resources :items

end

app/views/pages/home.html.erb
<div class="home-page">
  <div class='triangle2'></div>
  <div class='triangle'></div>
  <div class='beta-content'>
    <p>ßeta</p>
    <%= image_tag "avocado.gif" %>
  </div>
  <div>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
          <div class="home-holder">
            <div class="text-center">
              <%= image_tag "homelogo.png", class:"home-logo" %>
              <h3><%= t('.tagline2') %></h3>
            </div>
             <div class='text-center'>
              <p><%= link_to t('.sign_up'), new_username_path, class:'btn btn-home' %></p>
              <p id="signin" class="text-white-shadow"><%= link_to t('.sign_in'), new_user_session_path %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>