config/routes.rb
Rails.application.routes.draw do

  get 'tutoworlds/show'

  get 'recaps/show'
  post 'recaps/show'
  patch 'recaps/update'

  get 'fights/show'
  post 'fights/show'
  get 'fights/update'
  patch 'fights/update'

  get 'worlds/show'
  put 'worlds/update', to: 'worlds#update'
  scope '(:locale)', locale: /fr|es/ do
    root 'high_voltage/pages#show', id: 'home', as: :root_with_locale
    get '/pages/:id' => 'high_voltage/pages#show', :as => :page, :format => false
    resource :username, only: [:new, :create]
    devise_for :users
    resource :user, only: [:show, :update]
    get '/user/collection', to: 'users#collection'
    get '/user/stats', to: 'users#stats'
  end

  resources :items

end

app/controllers/usernames_controller.rb
class UsernamesController < ApplicationController
  prepend_before_filter :require_no_authentication
  skip_before_action    :authenticate_user!

  def new
  end

  def create
    username = params[:username]
    check = User.where(lowername: username.downcase).first

    if username.present?
      if check.nil?
        session[:username] = username
        redirect_to new_user_registration_path
      else
        flash[:alert] = I18n.t("usernames.create.flash.alert.already_taken")
        render :new
      end
    else
      flash[:alert] = I18n.t("usernames.create.flash.alert.empty")
      render :new
    end
  end

  private

  def require_no_authentication
    if current_user
      flash[:alert] = I18n.t("devise.failure.already_authenticated")
      redirect_to after_sign_in_path_for(current_user)
    end
  end
end

app/views/usernames/new.html.erb
<div class='makiswar-devise'>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
          <div class="card-bg-1">

            <%= link_to t('component.back'), root_path, class:'back-button' %>
            <%= image_tag "babyrice.gif", class:"text-center slideExpandUp", id:"baby-img" %>
            <h5 class='text-center text-white-shadow' id="hereisyourmaki"><%= t('.instruction') %><br><%= t('.instruction2') %></h5>
            <%= form_tag username_path, method: :post do %>
              <%= text_field_tag :username, '', placeholder:'Enter a cool name here!', class:'form-control' %><br>
              <%= submit_tag t('.submit'), class: "btn btn-success form-control", class:'confirm-action' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>